#ifndef LIBAFBEELDING_TGA_H
#define LIBAFBEELDING_TGA_H

#include "img.h"

#define TGA_MAP_NOCOLORMAP 0
#define TGA_MAP_COLORMAP 1

#define TGA_IMG_NOIMAGEDATA 0
#define TGA_IMG_COLORMAPPED 1
#define TGA_IMG_TRUECOLOR 2
#define TGA_IMG_BLACKWHITE 3
#define TGA_IMG_RUNLENGTH_COLORMAPPED 9
#define TGA_IMG_RUNLENGTH_TRUECOLOR 10
#define TGA_IMG_RUNLENGTH_BLACKWHITE 11

AFB_ERROR tga_load_file(IMAGE *img, char *path);

#endif
